static const char help[] =
"Build and view a tiny three-triangle mesh using DMPlex, and integrate a\n"
"scalar function over it.  Option prefixes tny_ and plex_view_.\n\n";

/* either build DMPlex via call to DMPlexCreateFromCellList()
    ./tiny
or by directly setting cones "by hand":
    ./tiny -tny_by_hand

compare these views:
    ./tiny -dm_view
    ./tiny -section_view
    ./tiny -tny_edges_view  FIXME:  should be replaced with something better
and -plex_view_xxx options (see plexview.h)

check it out: parallel refinement already works!:
    mpiexec -n 2 ./tiny -dm_refine 1 -plex_view_ranges -plex_view_coords

FIXME add option -tny_element P1|P2|P3

FIXME quadrature and integration of f(x,y) = e^{-x - 2 y}
*/

#include <petsc.h>
#include "plexview.h"

// Describe the mesh "triangle style" with separate numbering for cells and vertices.
static const int    dim = 2,
                    ncell = 3,
                    nvert = 5,
                    cells[9] = {0, 3, 2,  // 9 = ncell * (dim+1)
                                0, 2, 1,
                                2, 3, 4};
static const double coordverts[10] = {0.0, 0.0,  // 10 = nvert * dim
                                      0.0, 1.0,
                                      0.5, 1.0,
                                      1.0, 0.0,
                                      1.0, 1.0};

// Describe same mesh, but directly as DMPlex, i.e. by giving cell and
// edge cones in DAG.  These values are generated by DMPlexCreateFromCellList()
// internally, so they are redundant if we use that create method.
static const int npoint = 15,
                 ccone[3][3] = {{8,9,10},
                                {10,11,12},
                                {9,13,14}},
                 econe[7][2] = {{3,6},
                                {5,6},
                                {3,5},
                                {4,5},
                                {3,4},
                                {6,7},
                                {5,7}};

extern PetscErrorCode CreateMeshByHand(DM*);
extern PetscErrorCode CreateCoordinateSectionByHand(DM*);

int main(int argc,char **argv) {
    PetscErrorCode ierr;
    DM            dmplex;
    PetscSection  section;
    PetscBool     by_hand = PETSC_FALSE, edges_view = PETSC_FALSE;

    PetscInitialize(&argc,&argv,NULL,help);
    ierr = PetscOptionsBegin(PETSC_COMM_WORLD, "tny_", "options for tiny", "");CHKERRQ(ierr);
    ierr = PetscOptionsBool("-by_hand", "use by-hand construction",
                            "tiny.c", by_hand, &by_hand, NULL);CHKERRQ(ierr);
    ierr = PetscOptionsBool("-edges_view", "show coordinates of edge ends and centers (thus for P2) FIxME",
                            "tiny.c", edges_view, &edges_view, NULL);CHKERRQ(ierr);
    ierr = PetscOptionsEnd();

    if (by_hand) {
        ierr = CreateMeshByHand(&dmplex); CHKERRQ(ierr);
        ierr = CreateCoordinateSectionByHand(&dmplex); CHKERRQ(ierr);
    } else {
        PetscMPIInt rank;
        ierr = MPI_Comm_rank(PETSC_COMM_WORLD, &rank); CHKERRQ(ierr);
        if (rank == 0) { // create mesh on rank 0
            ierr = DMPlexCreateFromCellList(PETSC_COMM_WORLD,
                dim,ncell,nvert,dim+1,
                PETSC_TRUE,  // "interpolate" flag; TRUE means "topologically-interpolate"
                             // i.e. create edges (1D) from vertices (0D) and cells (2D)
                cells,dim,coordverts,
                &dmplex); CHKERRQ(ierr);
        } else { // empty mesh on rank > 0
            ierr = DMPlexCreateFromCellList(PETSC_COMM_WORLD,
                dim,0,0,dim+1,PETSC_TRUE,NULL,dim,NULL,&dmplex); CHKERRQ(ierr);
        }
    }

    // distribute mesh over processes using default partitioner
    {
        DM  distributedMesh = NULL;
        // overlap of 0 is appropriate to P2 etc. FEM:
        ierr = DMPlexDistribute(dmplex, 0, NULL, &distributedMesh);CHKERRQ(ierr);
        if (distributedMesh) {
          ierr = DMDestroy(&dmplex);CHKERRQ(ierr);
          dmplex  = distributedMesh;
        }
    }

    // reset names before viewing
    ierr = PetscObjectSetName((PetscObject)dmplex, "tiny mesh"); CHKERRQ(ierr);
    {
        DM           cdm;
        PetscSection csection;
        ierr = DMGetCoordinateDM(dmplex, &cdm); CHKERRQ(ierr);
        ierr = DMGetDefaultSection(cdm, &csection); CHKERRQ(ierr);
        ierr = PetscObjectSetName((PetscObject)csection, "vertex coordinate section"); CHKERRQ(ierr);
    }

    ierr = DMSetFromOptions(dmplex); CHKERRQ(ierr);
    ierr = DMViewFromOptions(dmplex, NULL, "-dm_view"); CHKERRQ(ierr);  // why not enabled by default?
    ierr = PlexViewFromOptions(dmplex); CHKERRQ(ierr);

    // Create nodes (degrees of freedom) for P2 elements using PetscSection.
    {
        int  j, vertexstart, edgeend;
        ierr = DMPlexGetDepthStratum(dmplex, 0, &vertexstart, NULL); CHKERRQ(ierr);
        ierr = DMPlexGetDepthStratum(dmplex, 1, NULL, &edgeend); CHKERRQ(ierr);
        // section has 1 dof on each vertex (depth==0) and (depth==1).
        ierr = PetscSectionCreate(PETSC_COMM_WORLD,&section); CHKERRQ(ierr);
        ierr = PetscObjectSetName((PetscObject)section, "P2 scalar section"); CHKERRQ(ierr);
        ierr = PetscSectionSetNumFields(section, 1); CHKERRQ(ierr);
        ierr = PetscSectionSetChart(section, vertexstart, edgeend); CHKERRQ(ierr);
        for (j = vertexstart; j < edgeend; ++j) {
            ierr = PetscSectionSetDof(section, j, 1); CHKERRQ(ierr);
            ierr = PetscSectionSetFieldDof(section, j, 0, 1); CHKERRQ(ierr);
        }
        ierr = PetscSectionSetUp(section); CHKERRQ(ierr);
        ierr = DMSetDefaultSection(dmplex, section); CHKERRQ(ierr);
        ierr = PetscObjectViewFromOptions((PetscObject)section,NULL,"-section_view"); CHKERRQ(ierr);
    }

    if (edges_view) {
        DM        cdm;
        Vec       coords;
        double    *acoords, ecx, ecy, vx[2], vy[2];
        int       j, vertexstart, edgestart, edgeend, off[2];
        const int *vertices;

        ierr = DMGetCoordinateDM(dmplex, &cdm); CHKERRQ(ierr);
        //ierr = DMGetLocalVector(dmplex, &v); CHKERRQ(ierr);
        //ierr = VecSet(v,0.0); CHKERRQ(ierr);
        ierr = DMGetCoordinatesLocal(dmplex,&coords); CHKERRQ(ierr);
        ierr = DMPlexGetDepthStratum(dmplex, 0, &vertexstart, NULL); CHKERRQ(ierr);
        ierr = DMPlexGetDepthStratum(dmplex, 1, &edgestart, &edgeend); CHKERRQ(ierr);
        //VecGetArray(v, &av);
        ierr = VecGetArray(coords, &acoords); CHKERRQ(ierr);
        for (j = edgestart; j < edgeend; j++) {
            ierr = DMPlexGetCone(dmplex, j, &vertices); CHKERRQ(ierr);
            off[0] = vertices[0] - vertexstart;
            off[1] = vertices[1] - vertexstart;
            vx[0] = acoords[2*off[0]+0];
            vy[0] = acoords[2*off[0]+1];
            vx[1] = acoords[2*off[1]+0];
            vy[1] = acoords[2*off[1]+1];
            ecx = 0.5 * (acoords[2*off[0]+0] + acoords[2*off[1]+0]);
            ecy = 0.5 * (acoords[2*off[0]+1] + acoords[2*off[1]+1]);
            ierr = PetscPrintf(PETSC_COMM_WORLD,
                "edge %d with ends (%g,%g) and (%g,%g) has center (%g,%g)\n",
                j,vx[0],vy[0],vx[1],vy[1],ecx,ecy); CHKERRQ(ierr);
        }
        //VecRestoreArray(v, &av);
        //ierr = DMRestoreLocalVector(dmplex, &v); CHKERRQ(ierr);
        ierr = VecRestoreArray(coords, &acoords); CHKERRQ(ierr);
    }

        //ierr = VecSetFromOptions(v); CHKERRQ(ierr);  // FIXME enables -v_vec_view?
        //ierr = PetscObjectViewFromOptions((PetscObject)v,NULL,"-vec_view"); CHKERRQ(ierr);
/*
        DMPlexGetTransitiveClosure(dmplex, 1, PETSC_TRUE, &numpts, &pts);
        for (j = 0; j < 2 * numpts; j += 2) {  // skip over orientations
            PetscSectionGetDof(section, pts[j], &dof);
            PetscSectionGetOffset(section, pts[j], &off);
            for (m = 0; m < dof; ++m) {
                av[off+m] = 1.0;
            }
        }
        DMPlexRestoreTransitiveClosure(dmplex, 1, PETSC_TRUE, &numpts, &pts);
*/

    PetscSectionDestroy(&section); DMDestroy(&dmplex);
    return PetscFinalize();
}


/* This function is essentially equivalent to using DMPlexCreateFromCellList().
Note that rank 0 gets the actual mesh and other ranks get an empty mesh.
See the implementations of
    DMPlexBuildFromCellList_Private()
    DMPlexCreateFromCellListParallel()
    DMPlexInterpolate()
    DMPlexBuildCoordinates_Private()      */
PetscErrorCode CreateMeshByHand(DM *dmplex) {
    PetscErrorCode ierr;
    int           j;
    PetscMPIInt   rank;
    ierr = MPI_Comm_rank(PETSC_COMM_WORLD,&rank); CHKERRQ(ierr);
    ierr = DMPlexCreate(PETSC_COMM_WORLD,dmplex); CHKERRQ(ierr);
    ierr = DMSetDimension(*dmplex,dim); CHKERRQ(ierr);
    if (rank == 0) {
        // set the total number of points (npoint = ncell + nvert + nedges)
        ierr = DMPlexSetChart(*dmplex, 0, npoint); CHKERRQ(ierr);
        // the points are cells, vertices, edges in that order
        // we only set cones for cells and edges
        for (j = 0; j < ncell; j++) {
            ierr = DMPlexSetConeSize(*dmplex, j, dim+1); CHKERRQ(ierr);
        }
        for (j = ncell + nvert; j < npoint; j++) {
            ierr = DMPlexSetConeSize(*dmplex, j, dim); CHKERRQ(ierr);
        }
        ierr = DMSetUp(*dmplex);
        for (j = 0; j < ncell; j++) {
            ierr = DMPlexSetCone(*dmplex, j, ccone[j]); CHKERRQ(ierr);
        }
        for (j = ncell + nvert; j < npoint; j++) {
            ierr = DMPlexSetCone(*dmplex, j, econe[j-ncell-nvert]); CHKERRQ(ierr);
        }
    } else {
        ierr = DMPlexSetChart(*dmplex, 0, 0); CHKERRQ(ierr);
    }
    // with cones we have only upward directions and no labels for the strata
    // (note: both Symmetrize & Stratify are required, and they must be in this order
    ierr = DMPlexSymmetrize(*dmplex); CHKERRQ(ierr);
    ierr = DMPlexStratify(*dmplex); CHKERRQ(ierr);
    return 0;
}

// Set up a PetscSection which holds vertex coordinates.
PetscErrorCode CreateCoordinateSectionByHand(DM *dmplex) {
    PetscErrorCode ierr;
    PetscSection  coordSection;
    DM            cdm;
    Vec           coordinates;
    double        *acoord;
    int           j, d, dim, vertexstart, vertexend;
    // you have to setup the PetscSection returned by DMGetCoordinateSection() first,
    // or else the Vec returned by DMCreateLocalVector() has zero size
    // (and thus seg faults)
    ierr = DMGetDimension(*dmplex, &dim); CHKERRQ(ierr);
    ierr = DMGetCoordinateSection(*dmplex, &coordSection); CHKERRQ(ierr);
    ierr = DMPlexGetDepthStratum(*dmplex, 0, &vertexstart, &vertexend); CHKERRQ(ierr);
    ierr = PetscSectionSetNumFields(coordSection, 1); CHKERRQ(ierr);
    ierr = PetscSectionSetFieldComponents(coordSection, 0, dim); CHKERRQ(ierr);
    ierr = PetscSectionSetChart(coordSection, vertexstart, vertexend); CHKERRQ(ierr);
    for (j = vertexstart; j < vertexend; j++) {
        ierr = PetscSectionSetDof(coordSection, j, dim); CHKERRQ(ierr);
        ierr = PetscSectionSetFieldDof(coordSection, j, 0, dim); CHKERRQ(ierr);
    }
    ierr = PetscSectionSetUp(coordSection); CHKERRQ(ierr);
    // now we can actually set up the coordinate Vec
    ierr = DMGetCoordinateDM(*dmplex, &cdm); CHKERRQ(ierr);
    ierr = DMCreateLocalVector(cdm, &coordinates); CHKERRQ(ierr);
    ierr = VecSetBlockSize(coordinates,dim); CHKERRQ(ierr);
    ierr = PetscObjectSetName((PetscObject) coordinates, "coordinates"); CHKERRQ(ierr);
    ierr = VecGetArray(coordinates, &acoord); CHKERRQ(ierr);
    for (j = 0; j < vertexend-vertexstart; j++) {
        for (d = 0; d < dim; ++d) {
            acoord[j*dim+d] = coordverts[j*dim+d];
        }
    }
    ierr = VecRestoreArray(coordinates, &acoord); CHKERRQ(ierr);
    // finally we tell the DM that it has coordinates
    ierr = DMSetCoordinatesLocal(*dmplex, coordinates); CHKERRQ(ierr);
    VecDestroy(&coordinates);
    return 0;
}

