#!/bin/bash

# run as 5 levels of refinement, quaddeg 2, solution case 1 (e.g.)
#   ./test_unfem.sh 5 2 1
# or
#   ./test_unfem.sh          (same as ./test_unfem.sh 4 1 0)

OPTIONS="-un_quaddeg ${2:-1} -un_case ${3:-0}"
# NOTE:   ${2:-1}  expands to $2 if set, otherwise as 1

area[0]=0.5
area[1]=0.1
area[2]=0.02
area[3]=0.005
area[4]=0.001
area[5]=0.0002
area[6]=0.00005
# NOTE:   trap.7.*, generated by area[6] above, is finest level tested

# generate .poly,.node,.ele files at each level of refinement
cd meshes/
triangle -pqa${area[0]} trap
for (( N=1; N<=${1:-4}; N++ )); do
    triangle -rpqa${area[$N]} trap.$N
done
cd ..

# generate .dat.node, .dat.ele files
for (( N=1; N<=${1:-4}; N++ )); do
    ./tri2petsc.py meshes/trap.$N trap.$N.dat
done

make unfem

# run unfem
for (( N=1; N<=${1:-4}; N++ )); do
    rm -f foo.txt
    ./unfem -un_mesh trap.$N.dat $OPTIONS -snes_fd -snes_max_funcs 100000 -log_view &> foo.txt
    'grep' "result for N" foo.txt
    'grep' SNESFunctionEval foo.txt | awk '{print $1,$2}'
    'grep' "Main Stage:" foo.txt | awk '{print $1,$2,$3,$4}'
done
rm -f foo.txt

